### ISSUE TITLE
How Can I Verify Days to Pull

### ISSUE THREAD

**Issue by richardgetz** [cabernetwork/provider_epg_tvguide#1]
I currently have this connected using DaddyLive. Is there a way to verify the pull number of days setting is working? As of now, I can only see the logs noting 2 days worth of data and Plex can only see 2 days out.

**Comment by rocky4546** [comment]
By default, I had it set to 2 days (which means less than 2 days).  It is because we hit the tvguide sites hard for program data when the days are increased.  However, if the plugin is stable, then you should increase it.  There is a couple of ways to see it.  The one I like is to have DEBUG turned on and then to request the xmltv.xml file.  For DaddyLive, it would be
http://ipaddress/daddylive/xmltv.xml
then you should see in the log something like this:
DEBUG:epg2xml Processing EPG data DaddyLive:default 2023-03-04
DEBUG:epg2xml Processing EPG data DaddyLive:default 2023-03-05
DEBUG:epg2xml Processing EPG data DaddyLive:default 2023-03-06
DEBUG:epg2xml Processing EPG data DaddyLive:default 2023-03-07
DEBUG:epg2xml Processing EPG data DaddyLive:default 2023-03-08
DEBUG:epg2xml Processing EPG data DaddyLive:default 2023-03-09
DEBUG:epg2xml Processing EPG data DaddyLive:default 2023-03-10
DEBUG:epg2xml Processing EPG data DaddyLive:default 2023-03-11
DEBUG:epg2xml Processing EPG data DaddyLive:default 2023-03-12
DEBUG:epg2xml Processing EPG data DaddyLive:default 2023-03-13
DEBUG:epg2xml Processing EPG data None:None None
this is when I have it set for 10 days.

**Comment by richardgetz** [comment]
I set it for 14 days yesterday, reset all my EPG data, and started a fresh scan. I still can't get more than 2 days. Is there any way for me to verify what it expects it should be pulling?

**Comment by rocky4546** [comment]
Assuming you are using this plugin. I am not aware of what you are asking.

**Comment by richardgetz** [comment]
Yes I'm using this plugin with DaddyLive. Under the instance I can choose the EPG look ahead days. It's set to 14, it only looks out 2 days. It sounds like there's no way to verify it other than to look at what the logs claim to have collected which means something is not getting updated properly on my system when changing. I'll start by changing to 10 days to see if that works instead of 14 I suppose.

**Comment by richardgetz** [comment]
For anyone who stumbles on a similar situation in the future setting it to the desired days and letting it get past what was pulled the first time worked for me. I am not sure why my resets didn't force it but it's working now.
